spring.application.name=prueba1

# Configuración de conexión a la BD
spring.datasource.url=jdbc:mysql://localhost:3306/tienda?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desactiva la advertencia de Open Session In View (Opcional)
spring.jpa.open-in-view=false